### ISSUE TITLE
Is dotnet/razor a tracked repo?

### ISSUE THREAD

**Issue by jaredpar** [timheuer/tacticview#16]
Based on triage this morning it seems like dotnet/razor is not being tracked by tactic view. Can we get it added? They need to see all the bad things we're doing :smile:

**Comment by timheuer** [comment]
This is now a tracked repo.  FYI the tracking is done on PRs not issues, so the latest `servicing-approved` one in the Issues list for Razor is not showing up because it's an Issue not a PR.

**Comment by jaredpar** [comment]
Ah okay, that was the mistake. Thanks!
