### ISSUE TITLE
Add the dotnet/roslyn-analyzers repo into the site

### ISSUE THREAD

**Issue by jeffhandley** [timheuer/tacticview#17]
Can we add [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) into TacticsView such that items with `Servicing-consider` and `Servicing-approved` from that repo show up on the site as well?

**Comment by timheuer** [comment]
Done, added to config in portal.  FYI i didn't see a `servicing-consider` label defined in the repo.  Also please remember TacticsView shows PRs only, not issues.
